using System;
using System.Collections.Generic;
using System.Text;
using Contollo.Rdel.ZipRunner.AI.Engine;

namespace Contollo.Rdel.ZipRunner.AI.Renderers
{
    internal sealed class MarkdownContextRenderer : IContextRenderer
    {
        public string Render(ContextAssemblyRequest request, ContextTemplate template, IList<ContextSection> sections)
        {
            var b = new StringBuilder();
            b.AppendLine("# AI Session Context");
            b.AppendLine();
            b.AppendLine("Session Mode: " + request.Kind);
            b.AppendLine("Template: " + template.Name);
            b.AppendLine("Generated By: Contollo RDEL / Context Assembly Engine");
            b.AppendLine("Generated UTC: " + DateTime.UtcNow.ToString("u"));
            b.AppendLine();
            foreach (var s in sections)
            {
                b.AppendLine("## " + s.Title);
                b.AppendLine();
                b.AppendLine(s.Content ?? string.Empty);
                b.AppendLine();
            }
            return b.ToString();
        }
    }
}
