using System;
using System.IO;
using System.Text;
using EnvDTE80;

namespace Contollo.Rdel.ZipRunner
{
    internal enum AiSessionContextKind { Initialize, Rehydrate, Continue }

    internal sealed class AiSessionContextBuilder
    {
        public string Build(AiSessionContextKind kind, DTE2 dte)
        {
            string solutionRoot = RdelSolutionLocator.GetSolutionRoot(dte);
            string selectedProjectRoot = RdelSolutionLocator.GetSelectedProjectRoot(dte);
            string repositoryName = string.IsNullOrWhiteSpace(solutionRoot) ? "Unknown" : Path.GetFileName(solutionRoot.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar));
            var builder = new StringBuilder();
            AppendHeader(builder, kind);
            AppendCoreInstructions(builder);
            AppendProjectPointers(builder, solutionRoot, selectedProjectRoot, repositoryName);
            if (kind == AiSessionContextKind.Initialize) AppendInitialize(builder, solutionRoot);
            else if (kind == AiSessionContextKind.Rehydrate) AppendRehydrate(builder, solutionRoot);
            else AppendContinue(builder, solutionRoot, dte);
            AppendRequestSlot(builder, kind);
            return builder.ToString();
        }

        private static void AppendHeader(StringBuilder b, AiSessionContextKind kind)
        { b.AppendLine("# AI Session Context"); b.AppendLine(); b.AppendLine("Session Mode: " + kind); b.AppendLine("Generated By: Contollo RDEL / AI Session Manager"); b.AppendLine("Generated UTC: " + DateTime.UtcNow.ToString("u")); b.AppendLine(); }

        private static void AppendCoreInstructions(StringBuilder b)
        {
            b.AppendLine("## Core Instructions For AI"); b.AppendLine();
            b.AppendLine("You are helping with a project that uses Neuro Commander Studio concepts and the RDEL package workflow.");
            b.AppendLine("Do not merely suggest code. Account for code.");
            b.AppendLine("When code or documentation changes are requested, generate a current-format RDEL ZIP package unless the user asks otherwise."); b.AppendLine();
            b.AppendLine("Required RDEL package root files: contollo-rdel.json and README.md.");
            b.AppendLine("When project context changes, update docs/context.md. Update docs/DECISIONS.md for architecture decisions and docs/memory.md for durable memory."); b.AppendLine();
            b.AppendLine("Current runner limitations: root README.md/context.md inside a package are metadata and are skipped; delete operations are not supported; patch/hunk mode is not supported; Commands are authoritative."); b.AppendLine();
            b.AppendLine("For documentation-only packages use Commands: [\"git status --porcelain\"].");
            b.AppendLine("For this VSIX project, do not use plain dotnet build unless explicitly requested. Use Visual Studio Build menu until VisualStudioMsBuild validation is implemented."); b.AppendLine();
        }

        private static void AppendProjectPointers(StringBuilder b, string solutionRoot, string selectedProjectRoot, string repositoryName)
        { b.AppendLine("## Project Pointers"); b.AppendLine(); b.AppendLine("Repository Name: " + N(repositoryName)); b.AppendLine("Solution Root: " + N(solutionRoot)); b.AppendLine("Selected Project Root: " + N(selectedProjectRoot)); b.AppendLine(); b.AppendLine("Public Context URLs, if GitHub Pages is enabled:"); b.AppendLine("- https://larrycarter.github.io/Contollo.Rdel.ZipRunner/docs/context.md"); b.AppendLine("- https://larrycarter.github.io/Contollo.Rdel.ZipRunner/docs/RDEL-AI-OPERATOR-GUIDE.md"); b.AppendLine("- https://larrycarter.github.io/Contollo.Rdel.ZipRunner/docs/RDEL-AI-SPEC.md"); b.AppendLine(); }

        private static void AppendInitialize(StringBuilder b, string root)
        { b.AppendLine("## Initialize Mode Purpose"); b.AppendLine(); b.AppendLine("Use this when the AI does not yet understand Neuro Commander Studio, RDEL, this repository, or the required package format."); b.AppendLine(); Doc(b, root, "docs/context.md", "Project Context"); Doc(b, root, "docs/RDEL-AI-OPERATOR-GUIDE.md", "AI Operator Guide"); Doc(b, root, "docs/RDEL-PACKAGE-AUTHORING-GUIDE.md", "Package Authoring Guide"); Doc(b, root, "docs/RDEL-AI-SPEC.md", "AI Specification"); Doc(b, root, "docs/ai-instructions.md", "AI Instructions"); }

        private static void AppendRehydrate(StringBuilder b, string root)
        { b.AppendLine("## Rehydrate Mode Purpose"); b.AppendLine(); b.AppendLine("Use this when switching AI providers, returning after time away, or recovering after a failed change."); b.AppendLine(); Doc(b, root, "docs/context.md", "Project Context"); Doc(b, root, "docs/memory.md", "Project Memory"); Doc(b, root, "docs/DECISIONS.md", "Architecture Decisions"); Git(b, root); }

        private static void AppendContinue(StringBuilder b, string root, DTE2 dte)
        { b.AppendLine("## Continue Mode Purpose"); b.AppendLine(); b.AppendLine("Use this when the AI already understands the project and only needs current task, active file, and relevant output."); b.AppendLine(); ActiveDoc(b, dte); Git(b, root); OutputHint(b, root); }

        private static void ActiveDoc(StringBuilder b, DTE2 dte)
        { b.AppendLine("## Active Document"); b.AppendLine(); try { if (dte != null && dte.ActiveDocument != null) { b.AppendLine("Name: " + dte.ActiveDocument.Name); b.AppendLine("Path: " + dte.ActiveDocument.FullName); } else b.AppendLine("No active document detected."); } catch (Exception ex) { b.AppendLine("Could not read active document: " + ex.Message); } b.AppendLine(); }

        private static void Git(StringBuilder b, string root)
        { b.AppendLine("## Git Status"); b.AppendLine(); if (string.IsNullOrWhiteSpace(root) || !Directory.Exists(root)) { b.AppendLine("Solution root not available."); b.AppendLine(); return; } try { RdelCommandResult r = RdelProcess.Run("git status --short", root); b.AppendLine("```text"); b.AppendLine(string.IsNullOrWhiteSpace(r.Output) ? "(clean or no output)" : r.Output.Trim()); b.AppendLine("```"); } catch (Exception ex) { b.AppendLine("Could not read git status: " + ex.Message); } b.AppendLine(); }

        private static void OutputHint(StringBuilder b, string root)
        { b.AppendLine("## Output Window / Error Context"); b.AppendLine(); b.AppendLine("Paste relevant Visual Studio Output, Build, Test, Git, Terminal, or Contollo RDEL output below if needed."); b.AppendLine(); b.AppendLine("```text"); b.AppendLine("[Paste output here]"); b.AppendLine("```"); b.AppendLine(); if (!string.IsNullOrWhiteSpace(root)) { b.AppendLine("RDEL run history path, if present:"); b.AppendLine("```text"); b.AppendLine(Path.Combine(root, ".contollo", "rdel", "runs")); b.AppendLine("```"); b.AppendLine(); } }

        private static void Doc(StringBuilder b, string root, string relativePath, string title)
        { b.AppendLine("## " + title); b.AppendLine(); if (string.IsNullOrWhiteSpace(root)) { b.AppendLine("Solution root not available. Read from repository docs if possible."); b.AppendLine(); return; } string path = Path.Combine(root, relativePath); if (!File.Exists(path)) { b.AppendLine("Not found locally: " + relativePath); b.AppendLine(); return; } string text = File.ReadAllText(path); b.AppendLine("Source: " + relativePath); b.AppendLine(); b.AppendLine("```markdown"); b.AppendLine(Trim(text, 8000)); b.AppendLine("```"); b.AppendLine(); }

        private static void AppendRequestSlot(StringBuilder b, AiSessionContextKind kind)
        { b.AppendLine("## User Request / Current Task"); b.AppendLine(); b.AppendLine(kind == AiSessionContextKind.Initialize ? "First, confirm you understand RDEL and the required current-format package workflow. Then wait for the specific task." : "[Paste or type the current task here.]"); b.AppendLine(); }

        private static string Trim(string text, int max) { if (string.IsNullOrWhiteSpace(text)) return string.Empty; return text.Length <= max ? text : text.Substring(0, max) + Environment.NewLine + Environment.NewLine + "[Truncated by AI Session Manager]"; }
        private static string N(string v) { return string.IsNullOrWhiteSpace(v) ? "(not available)" : v; }
    }
}
